import { FloralTemplate } from '../types.js';

export const FLORAL_TEMPLATES: FloralTemplate[] = [
  {
    id: 'FT-PEONY-BOTANICAL',
    name: 'Pastel Peony & English Rose Botanical Stage',
    subtitle: 'Contemporary Luxury Wedding & Reception Elegance',
    category: 'CONTEMPORARY',
    vibe: 'Romantic, Ethereal, Airy European Garden',
    basePrice: 385000,
    setupTimeHours: 7,
    stemEstimate: 4200,
    badgeText: 'Most Popular for Bangalore Weddings',
    tagline: 'Cascading blush peonies, David Austin garden roses, and airy eucalyptus runners with champagne gold backdrops.',
    colorPalette: [
      { name: 'Blush Pink', hex: '#FAD2E1' },
      { name: 'French Cream', hex: '#FFF9EC' },
      { name: 'Soft Sage', hex: '#D8E2DC' },
      { name: 'Champagne Gold', hex: '#E2C290' },
      { name: 'Dusty Lilac', hex: '#E8DFF5' },
    ],
    keyFlowers: [
      'Dutch Blush Peonies',
      'David Austin Juliet Roses',
      'White Hydrangeas',
      'Cascading Baby’s Breath (Gypsophila)',
      'Silver Dollar Eucalyptus',
    ],
    stemRecipe: [
      { flowerName: 'Dutch Blush Peonies', quantity: '350 Stems', color: 'Blush / Powder Pink', seasonality: 'Imported year-round' },
      { flowerName: 'David Austin Garden Roses', quantity: '650 Stems', color: 'Juliet Peach & Ivory', seasonality: 'All Season' },
      { flowerName: 'White & Soft Pink Hydrangeas', quantity: '180 Stems', color: 'Cloud White / Pink', seasonality: 'All Season' },
      { flowerName: 'Million Stars Gypsophila', quantity: '75 Bunches', color: 'Pure White', seasonality: 'Local Bangalore / Ooty' },
      { flowerName: 'Italian Ruscus & Silver Dollar Eucalyptus', quantity: '120 Bunches', color: 'Muted Sage Green', seasonality: 'Year-round' },
      { flowerName: 'Lisianthus & Ranunculus accents', quantity: '400 Stems', color: 'Buttercream & Champagne', seasonality: 'Fresh Weekly' },
    ],
    idealForVenues: [
      'The Leela Palace Ballroom',
      'Taj West End Grand Lawns',
      'Four Seasons Hotel Grand Ballroom',
      'JW Marriott Golfshire Lawn',
    ],
    lightingPairing: 'Warm 2700K amber pin-spots, fairy light canopy, and brushed champagne metallic pillar uplighting.',
    fragranceProfile: 'Natural English Damask Rose, Sweet Pea blossom, and fresh botanical eucalyptus mist.',
    inclusions: [
      '36ft Curved Arch Botanical Stage Backdrop with 3D floral density',
      'Matching Floral Mandap / Stage Framing with cascading floral overhangs',
      'Bridal Aisle Runner with 12 Elevated Mirrored Floral Pedestals',
      'Floral Photo-Op Wall (10x8 ft) with custom neon lettering ("Better Together")',
      '10 Luxury Banquet Table Floral Centers with floating candle scapes',
      'Bride & Groom Grand Floral Varmala Garlands (Light Rose & Jasmine weave)',
    ],
    fullDescription:
      'The Pastel Peony & English Rose Botanical Stage is our signature luxury European-inspired decor for grand weddings and receptions. Designed with soft, light-reflective pastel hues, it combines premium imported blooms with delicate foliage to create an unforgettable fairy-tale ambiance that looks magnificent in photography and 4K cinematography.',
    costBreakdown: [
      { category: 'Floral Procurement', item: 'Imported Peonies & Juliet Roses (1,000 stems)', quantity: 1, unit: 'Lot', rate: 145000, amount: 145000 },
      { category: 'Floral Procurement', item: 'Hydrangeas, Gyp, Lisianthus & Bangalore Foliage', quantity: 1, unit: 'Lot', rate: 75000, amount: 75000 },
      { category: 'Structure & Props', item: 'Curved Stage Arch, Pedestals & Mirrored Risers', quantity: 1, unit: 'Set', rate: 60000, amount: 60000 },
      { category: 'Lighting & FX', item: 'Amber Profile Spots, Fairy Canopy & Warm Uplights', quantity: 1, unit: 'Package', rate: 45000, amount: 45000 },
      { category: 'Artisanal Labor', item: 'Master Florists & Setup Crew (14 Technicians)', quantity: 1, unit: 'Shift', rate: 60000, amount: 60000 },
    ],
  },
  {
    id: 'FT-ROYAL-JASMINE-MOGRA',
    name: 'Royal Jasmine & Mogra Temple Sanctum',
    subtitle: 'Authentic South Indian Grand Heritage & Muhurtham Elegance',
    category: 'TRADITIONAL',
    vibe: 'Devotional, Aromatic, Regal Temple Heritage',
    basePrice: 320000,
    setupTimeHours: 8,
    stemEstimate: 8500,
    badgeText: 'Classic Bangalore Heritage Mandap',
    tagline: 'Thousands of fragrant Madurai Jasmine (Mogra) strings, golden brass Kuthuvilakku lamps, and pure white lotus sanctum.',
    colorPalette: [
      { name: 'Jasmine Pearl', hex: '#FFFFFA' },
      { name: 'Sacred Lotus Pink', hex: '#FFCCD5' },
      { name: 'Kunkum Sandalwood', hex: '#FDF0D5' },
      { name: 'Antique Temple Gold', hex: '#D4AF37' },
      { name: 'Banana Leaf Green', hex: '#95D5B2' },
    ],
    keyFlowers: [
      'Madurai Mogra (Jasmine Strings)',
      'Sacred Pink & White Lotuses',
      'Bangalore Tuberoses (Sugandharaja)',
      'Yellow Sevanti (Chrysanthemums)',
      'Marigold Garlands',
    ],
    stemRecipe: [
      { flowerName: 'Madurai Mogra (Jasmine) Hand-tied Strings', quantity: '4,500 Feet', color: 'Pristine White', seasonality: 'Fresh Daily' },
      { flowerName: 'Sacred Pink Temple Lotuses', quantity: '450 Blooms', color: 'Deep Sacred Pink', seasonality: 'Sourced Fresh' },
      { flowerName: 'Sugandharaja (Tuberoses) Dense Garlands', quantity: '1,200 Feet', color: 'Creamy White', seasonality: 'Local Karnataka' },
      { flowerName: 'Yellow & Orange Marigold Tassels', quantity: '800 Garlands', color: 'Golden Amber', seasonality: 'Hoskote / Gundlupet' },
      { flowerName: 'Betel Leaves & Mango Foliage Torans', quantity: '25 Bundles', color: 'Emerald Glossy Green', seasonality: 'Fresh Harvest' },
    ],
    idealForVenues: [
      'The Tamarind Tree, Kanakapura Road',
      'Gayathri Vihar, Palace Grounds',
      'Princess Shrine, Palace Grounds',
      'Ganjam Mantapa, Basavanagudi',
    ],
    lightingPairing: 'Temple oil brass Diya warm lighting, 2400K golden back-wash, and soft temple bell chandeliers.',
    fragranceProfile: 'Intoxicating Madurai Jasmine, temple camphor, fresh rose water, and pure sandalwood.',
    inclusions: [
      '4-Pillar Authentic Wooden & Brass Carved Mandap with ceiling Mogra weave',
      'Central Kundam floral ring with 100 Floating Lotuses in 6ft Brass Urli',
      'Grand Entrance Toranam with Jasmine strings, Mango leaf weave and brass bells',
      'Pathway with 16 Brass Kuthuvilakku pedestals wrapped in fresh tuberoses',
      'Stage backdrop with 3D Ganesha brass icon framed by lotus floral arch',
      'Traditional Heritage Rose Petal Welcome Shower for Groom & Bride Baraat',
    ],
    fullDescription:
      'Specially designed for auspicious South Indian Muhurthams and traditional weddings in Bangalore. Handcrafted using thousands of authentic Madurai Jasmine strings and fragrant Bangalore tuberoses, creating an aura of divine spirituality, serene beauty, and timeless grandeur.',
    costBreakdown: [
      { category: 'Floral Procurement', item: 'Madurai Mogra Jasmine (4,500 ft) & Fresh Lotuses', quantity: 1, unit: 'Lot', rate: 120000, amount: 120000 },
      { category: 'Floral Procurement', item: 'Sugandharaja Tuberoses & Marigold Tassels', quantity: 1, unit: 'Lot', rate: 45000, amount: 45000 },
      { category: 'Heritage Props', item: 'Carved Wood Mandap, Antique Brass Urlis & Deepams', quantity: 1, unit: 'Set', rate: 65000, amount: 65000 },
      { category: 'Lighting & Heritage FX', item: 'Warm Temple Glow, Profile Framing & Bells', quantity: 1, unit: 'Package', rate: 35000, amount: 35000 },
      { category: 'Artisanal Labor', item: 'Traditional Garland Weavers & Rigging Crew (16 Staff)', quantity: 1, unit: 'Shift', rate: 55000, amount: 55000 },
    ],
  },
  {
    id: 'FT-CELESTIAL-ORCHID',
    name: 'White Orchid & Cascading Gypsophila Celestial Arch',
    subtitle: 'Modern Minimalist Luxury & High-Fashion Reception Decor',
    category: 'CELESTIAL',
    vibe: 'Ultra-Modern, Sculptural, Monochromatic White Luxury',
    basePrice: 340000,
    setupTimeHours: 6,
    stemEstimate: 5100,
    badgeText: 'Ultra-Modern Minimalist',
    tagline: 'Sculptural Phalaenopsis orchids, billowing cloud-like baby’s breath formations, and crystal lucite pillars.',
    colorPalette: [
      { name: 'Snow White', hex: '#FFFFFF' },
      { name: 'Crystal Frost', hex: '#F0F4F8' },
      { name: 'Silver Mist', hex: '#E2E8F0' },
      { name: 'Soft Pearl', hex: '#FAF9F6' },
      { name: 'Lucite Glass', hex: '#EDF2F7' },
    ],
    keyFlowers: [
      'Phalaenopsis Long-Stem Orchids',
      'Dendrobium White Orchids',
      'Million Star Gypsophila Clouds',
      'White Calla Lilies',
      'Bleached Italian Ruscus',
    ],
    stemRecipe: [
      { flowerName: 'Cut Phalaenopsis Cascading Sprays', quantity: '280 Stems', color: 'Moonlight White', seasonality: 'Imported Premium' },
      { flowerName: 'White Dendrobium Orchids', quantity: '800 Stems', color: 'Pure Ivory White', seasonality: 'Bangalore / Thailand' },
      { flowerName: 'Million Stars Gypsophila (Heavy Clouds)', quantity: '140 Bunches', color: 'Snow White', seasonality: 'All Year' },
      { flowerName: 'White Calla Lilies & Anthuriums', quantity: '150 Stems', color: 'Porcelain White', seasonality: 'Specialty Import' },
      { flowerName: 'Bleached Ruscus & Lunaria (Silver Dollar)', quantity: '60 Bunches', color: 'Ghost White', seasonality: 'Dry Botanical' },
    ],
    idealForVenues: [
      'Conrad Bengaluru Grand Ballroom',
      'Sheraton Grand Whitefield',
      'The Oberoi Gardens, MG Road',
      'Shangri-La Hotel Grand Ballroom',
    ],
    lightingPairing: 'Cool-to-neutral 4000K crisp white stage profiles, submerged water LED crystals, and pinpoint wash lights.',
    fragranceProfile: 'Subtle white orchid nectar, morning dew, and refined ozone botanical notes.',
    inclusions: [
      'Floating "Cloud Formations" of Gypsophila and cascading Phalaenopsis Orchids',
      'Clear Acrylic Lucite Stage Pillars with internal LED illumination',
      'Mirror Finish White Stage Flooring with high-gloss reflective finish',
      'Suspended 24ft Floral Chandelier over couple’s seating',
      'Sculptural Minimalist Cake Table & Champagne Tower Floral Ring',
      '8 Grand Acrylic Floral Towers for VIP Guest Dining Tables',
    ],
    fullDescription:
      'Designed for couples and planners seeking high-fashion, ultra-modern visual aesthetics without visual clutter. The Celestial Arch relies on sculptural forms of white Phalaenopsis orchids and ethereal clouds of baby’s breath to create striking, timeless editorial photography.',
    costBreakdown: [
      { category: 'Floral Procurement', item: 'Phalaenopsis Orchids & Calla Lilies (Imported)', quantity: 1, unit: 'Lot', rate: 130000, amount: 130000 },
      { category: 'Floral Procurement', item: 'Dendrobiums & Gypsophila Cloud Bunches', quantity: 1, unit: 'Lot', rate: 65000, amount: 65000 },
      { category: 'Structure & Lucite Props', item: 'Clear Acrylic Pillars, Gloss White Floor & Rigging', quantity: 1, unit: 'Set', rate: 60000, amount: 60000 },
      { category: 'Lighting & Ambiance', item: 'Precision Pin-Spots & Crystal Overhead Rigging', quantity: 1, unit: 'Package', rate: 35000, amount: 35000 },
      { category: 'Artisanal Labor', item: 'Floral Sculptors & Rigging Engineers (12 Technicians)', quantity: 1, unit: 'Shift', rate: 50000, amount: 50000 },
    ],
  },
  {
    id: 'FT-BOHEMIAN-PAMPAS',
    name: 'Bohemian Pampas, Blush Protea & Terracotta Grove',
    subtitle: 'Chic Rustic Lawn & Sundowner Wedding Styling',
    category: 'BOHEMIAN',
    vibe: 'Earthy, Wildflower, Sun-drenched Chic',
    basePrice: 260000,
    setupTimeHours: 6,
    stemEstimate: 3100,
    badgeText: 'Outdoor Lawn & Sundowner Favorite',
    tagline: 'Fluffy feathery pampas grass, king proteas, sun-bleached palm fans, and handcrafted terracotta vessels.',
    colorPalette: [
      { name: 'Warm Terracotta', hex: '#E07A5F' },
      { name: 'Dusty Rose', hex: '#DDBEA9' },
      { name: 'Pampas Beige', hex: '#F4F1DE' },
      { name: 'Earthy Ochre', hex: '#F2CC8F' },
      { name: 'Olive Leaf', hex: '#81B29A' },
    ],
    keyFlowers: [
      'King Proteas (Blush & Pink)',
      'Natural Fluffy Pampas Grass Plumes',
      'Toffee & Cappuccino Roses',
      'Bleached Sun Palms & Bunny Tails',
      'Eucalyptus & Preserved Hydrangea',
    ],
    stemRecipe: [
      { flowerName: 'Giant Pampas Grass Fluffy Stems', quantity: '320 Stems', color: 'Natural Sand & Bleached Cream', seasonality: 'Preserved' },
      { flowerName: 'King Proteas & Queen Proteas', quantity: '45 Stems', color: 'Blush Terracotta', seasonality: 'Imported' },
      { flowerName: 'Cappuccino & Toffee Garden Roses', quantity: '450 Stems', color: 'Caramel & Dusty Peach', seasonality: 'All Season' },
      { flowerName: 'Sun Palm Spears & Fan Palms', quantity: '80 Pieces', color: 'Sun-Bleached Warm Gold', seasonality: 'Preserved' },
      { flowerName: 'Dried Bunny Tails, Wheat & Phalaris', quantity: '90 Bunches', color: 'Champagne Beige', seasonality: 'Botanical Dry' },
      { flowerName: 'Preserved Peach & Terracotta Hydrangeas', quantity: '60 Blooms', color: 'Soft Coral Peach', seasonality: 'Year-round' },
    ],
    idealForVenues: [
      'The Courtyard, Shanthi Nagar',
      'The Beginning, Sarjapur Road',
      'Breeze Garden Lawn, Yelahanka',
      'Jade 735 Retreat & Villa, Bangalore',
    ],
    lightingPairing: 'Edison bulb strings, woven rattan pendant lamps, and low-angle warm floodlights on terracotta urns.',
    fragranceProfile: 'Warm cedarwood, sweet amber, wild lavender, and dried botanical honey.',
    inclusions: [
      'Circular Double-Ring Bohemian Arch (8ft diameter) loaded with pampas and proteas',
      'Aisle runway lined with 20 Handcrafted Terracotta Urns bursting with dried botanicals',
      'Lounge seating photo-booth with rattan peacock chairs & vintage kilim rugs',
      'Rustic Wooden Welcome Easel with dried flower floral spray',
      'Bar counter floral cladding with textured palm fan installation',
      '8 Low-Seating Grazing Table floral runners with pillar candles',
    ],
    fullDescription:
      'Ideal for sun-kissed outdoor lawns, cocktail sundowners, and boho-chic weddings across Bangalore. Blending soft dried textures with vibrant fresh florals and artisanal terracotta urns, this setup brings unmatched organic warmth and effortless modern charm.',
    costBreakdown: [
      { category: 'Floral & Botanical', item: 'Pampas Plumes, King Proteas & Toffee Roses', quantity: 1, unit: 'Lot', rate: 95000, amount: 95000 },
      { category: 'Dried Botanical Accents', item: 'Sun Palms, Bunny Tails & Preserved Blooms', quantity: 1, unit: 'Lot', rate: 45000, amount: 45000 },
      { category: 'Boho Furniture & Urns', item: 'Peacock Chairs, Terracotta Vessels & Kilim Rugs', quantity: 1, unit: 'Set', rate: 45000, amount: 45000 },
      { category: 'Lighting & Rattan', item: 'Edison Bulbs & Woven Rattan Light Fixtures', quantity: 1, unit: 'Package', rate: 35000, amount: 35000 },
      { category: 'Artisanal Labor', item: 'Styling Designers & Setup Craftsmen (10 Staff)', quantity: 1, unit: 'Shift', rate: 40000, amount: 40000 },
    ],
  },
  {
    id: 'FT-FRENCH-HYDRANGEA',
    name: 'French Lavender, Blue Hydrangea & Meadow Gazebo',
    subtitle: 'European Spring Pastel Garden & Day Wedding Symphony',
    category: 'GARDEN',
    vibe: 'Whimsical, Fresh, Pastel Garden Meadow',
    basePrice: 360000,
    setupTimeHours: 7,
    stemEstimate: 4600,
    badgeText: 'Pastel Garden Dream',
    tagline: 'Periwinkle blue hydrangeas, French lavender sprays, white delphiniums, and blooming wildflower meadow pathways.',
    colorPalette: [
      { name: 'Hydrangea Blue', hex: '#A2D2FF' },
      { name: 'Lavender Mist', hex: '#BDB2FF' },
      { name: 'Buttercup Cream', hex: '#FDFFB6' },
      { name: 'Powder Rose', hex: '#FFC6FF' },
      { name: 'Meadow Grass', hex: '#CAFFBF' },
    ],
    keyFlowers: [
      'Dutch Blue & Purple Hydrangeas',
      'Tall White & Sky Blue Delphiniums',
      'French Fresh Lavender Sprigs',
      'Peach & Pink Lisianthus',
      'Sweet Peas & Queen Anne’s Lace',
    ],
    stemRecipe: [
      { flowerName: 'Dutch Blue Hydrangeas', quantity: '240 Blooms', color: 'Sky Blue / Periwinkle', seasonality: 'Imported' },
      { flowerName: 'Delphinium Stems (Blue & White)', quantity: '350 Stems', color: 'Royal Sky Blue & Pure White', seasonality: 'Cold Region' },
      { flowerName: 'French Lavender Sprigs', quantity: '180 Bunches', color: 'Rich Violet / Lilac', seasonality: 'Fresh Seasonal' },
      { flowerName: 'Lisianthus (Double Flowered)', quantity: '500 Stems', color: 'Soft Peach & Rose Cream', seasonality: 'Bangalore / Ooty' },
      { flowerName: 'Queen Anne’s Lace & Matricaria Chamomile', quantity: '95 Bunches', color: 'Airy White', seasonality: 'Fresh Local' },
      { flowerName: 'Italian Ruscus & Jasmine Vine Foliage', quantity: '110 Bunches', color: 'Spring Green', seasonality: 'Year-round' },
    ],
    idealForVenues: [
      'The Glass House, Taj West End',
      'Angsana Oasis Resort Lawns',
      'Ranch at Big Banyan Tree',
      'Golden Palms Resort & Spa',
    ],
    lightingPairing: 'Natural dappled sunlight complement with warm 3000K fairy tree wraps and wrought iron lantern pillars.',
    fragranceProfile: 'French lavender fields, sweet chamomile, fresh cut grass, and lilacs.',
    inclusions: [
      '4-Sided Wrought Iron Gazebo completely swathed in Hydrangea and Delphinium blooms',
      '"Growing Ground Meadow" along entire stage base with 80 individual flower boxes',
      '100ft Floral Petal Carpet in Ombre Blue-to-White gradient for aisle walk',
      'Delicate Hanging Floral Clouds suspended with invisible monofilament line',
      'Custom Botanical Welcome Board with fresh flower frame & custom calligraphy',
      'Bridal Bouquet with cascading French Lavender, Blue Hydrangeas & Silk Ribbon',
    ],
    fullDescription:
      'A breathtaking European garden meadow brought to life in Bangalore. Featuring cool blues, soft lilacs, and fresh botanical greens, this theme turns open-air and glasshouse venues into an enchanting wonderland.',
    costBreakdown: [
      { category: 'Floral Procurement', item: 'Dutch Blue Hydrangeas & Delphinium Stems', quantity: 1, unit: 'Lot', rate: 135000, amount: 135000 },
      { category: 'Floral Procurement', item: 'Lavender Sprigs, Lisianthus & Chamomile Bunches', quantity: 1, unit: 'Lot', rate: 65000, amount: 65000 },
      { category: 'Iron Gazebo & Props', item: 'Wrought Iron Meadow Gazebo & Ground Boxes', quantity: 1, unit: 'Set', rate: 55000, amount: 55000 },
      { category: 'Lighting & Fairy Wire', item: 'Fairy Tree Wraps & Vintage Iron Lanterns', quantity: 1, unit: 'Package', rate: 45000, amount: 45000 },
      { category: 'Artisanal Labor', item: 'European Floral Designers & Garden Crew (14 Staff)', quantity: 1, unit: 'Shift', rate: 60000, amount: 60000 },
    ],
  },
  {
    id: 'FT-MARIGOLD-SUNFLOWER-HALDI',
    name: 'Marigold Sunset & Gilded Sunflower Haldi Canopy',
    subtitle: 'Vibrant Traditional Haldi, Mehendi & Sangeet Sunshine Carnival',
    category: 'CELEBRATION',
    vibe: 'Joyful, Energetic, Radiant Indian Carnival',
    basePrice: 180000,
    setupTimeHours: 5,
    stemEstimate: 9500,
    badgeText: 'High Energy Haldi Special',
    tagline: 'Swirling yellow and orange marigold vortex canopies, giant sunflowers, brass urli water baths, and festive yellow drapes.',
    colorPalette: [
      { name: 'Sunshine Yellow', hex: '#FFD166' },
      { name: 'Tangerine Orange', hex: '#F77F00' },
      { name: 'Marigold Gold', hex: '#FCBF49' },
      { name: 'Kesar Ochre', hex: '#EAE2B7' },
      { name: 'Fresh Green', hex: '#06D6A0' },
    ],
    keyFlowers: [
      'Gundlupet Golden Marigolds (Gende Ka Phool)',
      'Orange Marigold Dense Garlands',
      'Giant Fresh Sunflowers',
      'Yellow Sevanti (Chrysanthemums)',
      'Mango Leaves & Coconut Palm Fronds',
    ],
    stemRecipe: [
      { flowerName: 'Yellow & Orange Marigold Garlands', quantity: '2,800 Metres', color: 'Golden Yellow & Flame Orange', seasonality: 'Karnataka Harvest' },
      { flowerName: 'Giant Field Sunflowers', quantity: '220 Blooms', color: 'Vibrant Solar Yellow', seasonality: 'Fresh Sourced' },
      { flowerName: 'Yellow Chrysanthemums (Sevanti)', quantity: '120 Kgs', color: 'Bright Lemon Yellow', seasonality: 'Local Bangalore' },
      { flowerName: 'Fresh Mango Leaves & Coconut Torans', quantity: '40 Bundles', color: 'Forest Green', seasonality: 'Daily Harvest' },
      { flowerName: 'Loose Yellow Rose & Marigold Petals for Shower', quantity: '50 Kgs', color: 'Gold / Orange', seasonality: 'Fresh Packed' },
    ],
    idealForVenues: [
      'Poolside Lawns at Clarks Exotica Resort',
      'Olde Bangalore Resort Lawn',
      'Moongate Events Venue, Yelahanka',
      'Private Farmhouses in Sarjapur / Kanakapura',
    ],
    lightingPairing: 'Festive festoon warm bulbs, bamboo tiki torch accents, and vibrant color uplights for evening transitions.',
    fragranceProfile: 'Zesty marigold petal essence, fresh crushed turmeric, mogra incense, and citrus lemon blossom.',
    inclusions: [
      'Canopy of 100 Hanging Marigold Tassels cascading above couple seating',
      'Giant 7ft Brass Urli with Floating Marigolds & Rose Petals for Haldi Ceremony',
      'Handcrafted Sunflower & Bamboo Photo Booth with festive yellow scooter prop',
      'Colorful Festive Drapes in Butter Yellow, Rani Pink & Parrot Green accents',
      'Mehendi Cabana with cushion seating, bolsters and marigold hangings',
      '50kg Rose & Marigold Petal Buckets with brass bowls for Flower Shower (Phoolon ki Holi)',
    ],
    fullDescription:
      'The quintessential celebration decor for energetic Haldi and Mehendi functions in Bangalore. Bursting with cheerful sunflowers and rich fragrant marigold garlands, this design guarantees high-spirited memories and spectacular photo moments.',
    costBreakdown: [
      { category: 'Floral Procurement', item: 'Bulk Marigold Garlands (2,800m) & 120kg Sevanti', quantity: 1, unit: 'Lot', rate: 65000, amount: 65000 },
      { category: 'Floral Procurement', item: 'Sunflowers & Petal Shower Baskets (50kg)', quantity: 1, unit: 'Lot', rate: 25000, amount: 25000 },
      { category: 'Props & Furniture', item: 'Giant Brass Urli, Bamboo Canopies & Haldi Props', quantity: 1, unit: 'Set', rate: 35000, amount: 35000 },
      { category: 'Drapes & Festoon', item: 'Canopy Ceiling Drapes & Festoon Lighting Grid', quantity: 1, unit: 'Package', rate: 25000, amount: 25000 },
      { category: 'Artisanal Labor', item: 'Marigold Tassel Riggers & Event Decorators (12 Staff)', quantity: 1, unit: 'Shift', rate: 30000, amount: 30000 },
    ],
  },
  {
    id: 'FT-CRIMSON-ROSE-GALA',
    name: 'Crimson Red Baccara Rose & Crystal Grand Gala',
    subtitle: 'High-Glamour Red-Carpet Reception & Sangeet Opulence',
    category: 'HIGH_GLAMOUR',
    vibe: 'Dramatic, Luxurious, Velvet Passion & Crystal Sparkle',
    basePrice: 420000,
    setupTimeHours: 8,
    stemEstimate: 6200,
    badgeText: 'Ultimate Luxury Evening Glamour',
    tagline: 'Deep velvet crimson Grand Gala roses, cascading burgundy amaranthus, and opulent multi-tier crystal chandeliers.',
    colorPalette: [
      { name: 'Crimson Velvet', hex: '#590D22' },
      { name: 'Ruby Wine', hex: '#800F2F' },
      { name: 'Rosewood Blush', hex: '#A4133C' },
      { name: 'Gilded Gold', hex: '#D4AF37' },
      { name: 'Deep Onyx', hex: '#1B1B1E' },
    ],
    keyFlowers: [
      'Imported Grand Gala Red Roses',
      'Black Baccara Velvet Roses',
      'Cascading Burgundy Amaranthus',
      'Red Anthuriums & Orchids',
      'Gilded Gold Ruscus Foliage',
    ],
    stemRecipe: [
      { flowerName: 'Grand Gala & Black Baccara Red Roses', quantity: '3,800 Stems', color: 'Deep Velvet Crimson & Wine', seasonality: 'Bangalore & Pune' },
      { flowerName: 'Cascading Burgundy Amaranthus Tails', quantity: '450 Stems', color: 'Dark Wine Red', seasonality: 'Imported Specialty' },
      { flowerName: 'Red Anthuriums & Mokara Orchids', quantity: '300 Stems', color: 'Glossy Ruby Red', seasonality: 'Fresh Import' },
      { flowerName: 'Spray Carmine Roses', quantity: '800 Stems', color: 'Rich Scarlet', seasonality: 'All Season' },
      { flowerName: 'Gold-leaf Dipped Ruscus & Magnolia Leaves', quantity: '120 Bunches', color: 'Metallic Antique Gold', seasonality: 'Artisan Coated' },
    ],
    idealForVenues: [
      'Grand Ballroom at The Ritz-Carlton, Residency Rd',
      'ITC Gardenia Mysore Hall',
      'The Lalit Ashok Kalinga Grand Hall',
      'JW Marriott Vittal Mallya Ballroom',
    ],
    lightingPairing: 'Dramatic 2800K low-key theatrical stage follow-spots, crystal refraction lights, and 100 pillar candle hurricanes.',
    fragranceProfile: 'Rich Damask red rose absolute, spiced vanilla, oud, and amber resin.',
    inclusions: [
      '40ft Full Red Rose Paved Floral Wall Backdrop with 3,800 velvety roses',
      '5 Multi-Tier Bohemian Crystal Chandeliers suspended above stage floor',
      'Black Mirror Stage Flooring reflecting red florals and crystal lights',
      '12 Elevated Floral Vases with cascading Amaranthus tails for guest tables',
      'Grand Grand Entrance Tunnel draped with gold mesh and red floral arches',
      'Bar Back installation with embedded illuminated red rose niches',
    ],
    fullDescription:
      'For clients dreaming of absolute luxury, Hollywood red-carpet glam, and royal drama. Dressed in thousands of velvety dark red roses and dripping crystals, this design is the pinnacle of grand evening celebrations.',
    costBreakdown: [
      { category: 'Floral Procurement', item: 'Grand Gala & Baccara Red Roses (3,800 stems)', quantity: 1, unit: 'Lot', rate: 160000, amount: 160000 },
      { category: 'Floral Procurement', item: 'Burgundy Amaranthus, Red Anthuriums & Gold Foliage', quantity: 1, unit: 'Lot', rate: 75000, amount: 75000 },
      { category: 'Crystal & Stage Props', item: 'Crystal Chandeliers, Black Mirror Floor & Gold Tunnel', quantity: 1, unit: 'Set', rate: 75000, amount: 75000 },
      { category: 'Theatrical Lighting', item: 'Theatrical Spotlights, Pillar Candles & Dimmer Rigs', quantity: 1, unit: 'Package', rate: 45000, amount: 45000 },
      { category: 'Artisanal Labor', item: 'Master Rose Sculptors & Staging Crew (16 Technicians)', quantity: 1, unit: 'Shift', rate: 65000, amount: 65000 },
    ],
  },
  {
    id: 'FT-LOTUS-WATERWAY',
    name: 'Lotus Waterway & Gilded Brass Temple Sanctum',
    subtitle: 'Sacred Pink Lotus, Traditional Water Urli & Heritage Bells',
    category: 'HERITAGE',
    vibe: 'Regal, Sacred, Soothing Waterway Serenity',
    basePrice: 380000,
    setupTimeHours: 8,
    stemEstimate: 7000,
    badgeText: 'Heritage Royalty Favorite',
    tagline: 'Waterway aisle with floating blooming pink lotuses, traditional brass temple pillars, and fragrant mogra tassels.',
    colorPalette: [
      { name: 'Sacred Lotus Pink', hex: '#FFB5A7' },
      { name: 'Mogra White', hex: '#F8F9FA' },
      { name: 'Antique Brass', hex: '#C5A059' },
      { name: 'Kashmiri Saffron', hex: '#F4A261' },
      { name: 'Deep Emerald', hex: '#2D6A4F' },
    ],
    keyFlowers: [
      'Sacred Indian Pink Lotuses',
      'White Floating Water Lilies',
      'Madurai Jasmine (Mogra) Strands',
      'Orange & Yellow Marigold Rosettes',
      'Fragrant Pink Damask Desi Roses',
    ],
    stemRecipe: [
      { flowerName: 'Sacred Blooming Pink Lotuses', quantity: '600 Blooms', color: 'Sacred Petal Pink', seasonality: 'Fresh Farm Picked' },
      { flowerName: 'Fresh Mogra Strands for Cascades', quantity: '3,200 Feet', color: 'Pristine Jasmine White', seasonality: 'Fresh Harvest' },
      { flowerName: 'Desi Pink Paneer Rose Petals', quantity: '80 Kgs', color: 'Deep Scented Pink', seasonality: 'Local Karnataka' },
      { flowerName: 'Yellow Sevanti & Marigold Rosettes', quantity: '1,200 Pieces', color: 'Warm Gold', seasonality: 'All Year' },
      { flowerName: 'Banana Stem Carved Pillars with Lotus Crowns', quantity: '16 Pillars', color: 'Natural Jade Green', seasonality: 'Fresh Hand-Carved' },
    ],
    idealForVenues: [
      'Ganjam Mantapa, Bull Temple Road',
      'The Tamarind Tree Heritage Pond',
      'Shubh Muhurat Mandap, Palace Grounds',
      'Temple Tree Leisure, Bellandur',
    ],
    lightingPairing: 'Underwater warm LED submersible pucks, thousands of floating wax diyas, and warm brass floodlights.',
    fragranceProfile: 'Paneer rose essence, holy lotus nectar, Madurai jasmine, and pure camphor.',
    inclusions: [
      'Floating Lotus Waterway aisle built with transparent safety glass bridging water basins',
      '4-Pillar Heritage Brass Temple Structure with Mogra ceiling weave & lotus pendants',
      'Backdrop with 108 Carved Brass Niches each housing an illuminated Lotus bloom',
      'Aisle lined with 24 Giant Antique Brass Urlis brimming with rose petals & floating lotuses',
      'Grand Entrance Bell Archway with 51 tuned brass temple bells ringing in the breeze',
      'Traditional Paneer Chombu welcome water spray for all arriving guests',
    ],
    fullDescription:
      'Inspired by the sacred temple sanctums and royal courtyards of South India. This design places pristine pink lotuses and floating waterscapes at the heart of the ceremony, delivering an aura of serenity, tradition, and regal elegance.',
    costBreakdown: [
      { category: 'Floral Procurement', item: 'Sacred Pink Lotuses (600 blooms) & Mogra (3,200 ft)', quantity: 1, unit: 'Lot', rate: 140000, amount: 140000 },
      { category: 'Floral Procurement', item: 'Desi Rose Petals (80kg) & Sevanti Rosettes', quantity: 1, unit: 'Lot', rate: 50000, amount: 50000 },
      { category: 'Heritage Water Structure', item: 'Water Basin Glass Bridges & 24 Giant Brass Urlis', quantity: 1, unit: 'Set', rate: 80000, amount: 80000 },
      { category: 'Lighting & Diya Setup', item: 'Underwater LEDs, Float Diyas & Bell Rigging', quantity: 1, unit: 'Package', rate: 45000, amount: 45000 },
      { category: 'Artisanal Labor', item: 'Heritage Temple Florists & Carpentry Crew (16 Staff)', quantity: 1, unit: 'Shift', rate: 65000, amount: 65000 },
    ],
  },
];
